### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Liays-eng** [TheonlyIcebear/Bloxflip-Smart-Bet#22]
ERROR:root:A error has occured at 16:23:35 04
Traceback (most recent call last):
  File "C:\Users\User\Contacts\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 18, in __init__
    self.getConfig()
  File "C:\Users\User\Contacts\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 164, in getConfig
    self.browser = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 102.0.5005.61 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x004D7413+2389011]
	Ordinal0 [0x00469F61+1941345]
	Ordinal0 [0x0035C658+837208]
	Ordinal0 [0x0037C773+968563]
	Ordinal0 [0x0037837A+951162]
	Ordinal0 [0x00375C51+941137]
	Ordinal0 [0x003A8C80+1150080]
	Ordinal0 [0x003A88DA+1149146]
	Ordinal0 [0x003A3F66+1130342]
	Ordinal0 [0x0037E546+976198]
	Ordinal0 [0x0037F456+980054]
	GetHandleVerifier [0x00689632+1727522]
	GetHandleVerifier [0x0073BA4D+2457661]
	GetHandleVerifier [0x0056EB81+569713]
	GetHandleVerifier [0x0056DD76+566118]
	Ordinal0 [0x00470B2B+1968939]
	Ordinal0 [0x00475988+1989000]
	Ordinal0 [0x00475A75+1989237]
	Ordinal0 [0x0047ECB1+2026673]
	BaseThreadInitThunk [0x7696FA29+25]
	RtlGetAppContainerNamedObjectPath [0x770E7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x770E7A4E+238]

**Comment by TheonlyIcebear** [comment]
Fixed
