### ISSUE TITLE
issue with crash

### ISSUE THREAD

**Issue by Snickerswith** [TheonlyIcebear/Bloxflip-Smart-Bet#23]
ERROR:root:A error has occured at 16:37:36 04
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Random things\Bloxflip-Smart-Bet-main\Martingale.py", line 19, in __init__
    self.sendBets()
  File "C:\Users\Owner\Downloads\Random things\Bloxflip-Smart-Bet-main\Martingale.py", line 319, in sendBets
    browser.find_element_by_css_selector(".MuiButtonBase-root.MuiButton-root.MuiButton-contained.jss142.MuiButton-containedPrimary").click()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 814, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".MuiButtonBase-root.MuiButton-root.MuiButton-contained.jss142.MuiButton-containedPrimary"}
  (Session info: chrome=101.0.4951.67)
Stacktrace:
Backtrace:
	Ordinal0 [0x00A57413+2389011]
	Ordinal0 [0x009E9F61+1941345]
	Ordinal0 [0x008DC658+837208]
	Ordinal0 [0x009091DD+1020381]
	Ordinal0 [0x0090949B+1021083]
	Ordinal0 [0x00936032+1204274]
	Ordinal0 [0x00924194+1130900]
	Ordinal0 [0x00934302+1196802]
	Ordinal0 [0x00923F66+1130342]
	Ordinal0 [0x008FE546+976198]
	Ordinal0 [0x008FF456+980054]
	GetHandleVerifier [0x00C09632+1727522]
	GetHandleVerifier [0x00CBBA4D+2457661]
	GetHandleVerifier [0x00AEEB81+569713]
	GetHandleVerifier [0x00AEDD76+566118]
	Ordinal0 [0x009F0B2B+1968939]
	Ordinal0 [0x009F5988+1989000]
	Ordinal0 [0x009F5A75+1989237]
	Ordinal0 [0x009FECB1+2026673]
	BaseThreadInitThunk [0x76A4FA29+25]
	RtlGetAppContainerNamedObjectPath [0x771C7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x771C7A4E+238]

**Comment by TheonlyIcebear** [comment]
Fixed
