### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MaxMady** [TheonlyIcebear/Bloxflip-Smart-Bet#25]
```
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 18, in __init__
    self.getConfig()
  File "C:\Users\User\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 178, in getConfig
    self.browser = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
```Im getting this error when I try to run Martingale.py file. Can anyone help me with this?

**Comment by TheonlyIcebear** [comment]
Is that the full errors.txt? by the looks of it chromedriver.exe don't exit

**Comment by MaxMady** [comment]
```
ERROR:root:A error has occured at 08:34:36 08
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 18, in __init__
    self.getConfig()
  File "C:\Users\User\Desktop\Bloxflip-Smart-Bet-main\Martingale.py", line 178, in getConfig
    self.browser = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 102
Current browser version is 101.0.4951.67 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x002AD953+2414931]
	Ordinal0 [0x0023F5E1+1963489]
	Ordinal0 [0x0012C6B8+837304]
	Ordinal0 [0x0014CAE3+969443]
	Ordinal0 [0x001486FA+952058]
	Ordinal0 [0x00145FB1+942001]
	Ordinal0 [0x00179100+1151232]
	Ordinal0 [0x00178D5A+1150298]
	Ordinal0 [0x001742B6+1131190]
	Ordinal0 [0x0014E860+976992]
	Ordinal0 [0x0014F756+980822]
	GetHandleVerifier [0x0051CC62+2510274]
	GetHandleVerifier [0x0050F760+2455744]
	GetHandleVerifier [0x0033EABA+551962]
	GetHandleVerifier [0x0033D916+547446]
	Ordinal0 [0x00245F3B+1990459]
	Ordinal0 [0x0024A898+2009240]
	Ordinal0 [0x0024A985+2009477]
	Ordinal0 [0x00253AD1+2046673]
	BaseThreadInitThunk [0x767C6739+25]
	RtlGetFullPathName_UEx [0x77C78FEF+1215]
	RtlGetFullPathName_UEx [0x77C78FBD+1165]
	(No symbol) [0x00000000]

```This is the full error

**Comment by TheonlyIcebear** [comment]
Chromedriver not up to date. delete the chromedriver.exe and try again
