### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by LachanSPU** [TheonlyIcebear/Bloxflip-Smart-Bet#28]
ERROR:root:A error has occured at 19:16:30 07
Traceback (most recent call last):
  File "C:\Users\marti\Desktop\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\StreakBased.py", line 157, in getConfig
    self.browser = webdriver.Chrome("chromedriver.exe", chrome_options=options)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\marti\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 102.0.5005.63 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00697413+2389011]
	Ordinal0 [0x00629F61+1941345]
	Ordinal0 [0x0051C658+837208]
	Ordinal0 [0x0053C773+968563]
	Ordinal0 [0x0053837A+951162]
	Ordinal0 [0x00535C51+941137]
	Ordinal0 [0x00568C80+1150080]
	Ordinal0 [0x005688DA+1149146]
	Ordinal0 [0x00563F66+1130342]
	Ordinal0 [0x0053E546+976198]
	Ordinal0 [0x0053F456+980054]
	GetHandleVerifier [0x00849632+1727522]
	GetHandleVerifier [0x008FBA4D+2457661]
	GetHandleVerifier [0x0072EB81+569713]
	GetHandleVerifier [0x0072DD76+566118]
	Ordinal0 [0x00630B2B+1968939]
	Ordinal0 [0x00635988+1989000]
	Ordinal0 [0x00635A75+1989237]
	Ordinal0 [0x0063ECB1+2026673]
	BaseThreadInitThunk [0x75D07BA9+25]
	RtlInitializeExceptionChain [0x770CB7DB+107]
	RtlClearBits [0x770CB75F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marti\Desktop\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\StreakBased.py", line 18, in __init__
    self.getConfig()
  File "C:\Users\marti\Desktop\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\StreakBased.py", line 160, in getConfig
    uiptiny("If your not sure how to update just uninstall then reinstall chrome", "yellow")
NameError: name 'uiptiny' is not defined

**Comment by TheonlyIcebear** [comment]
Fixed
