### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by b0ltcore** [TheonlyIcebear/Bloxflip-Smart-Bet#31]
it logs in and then it gives me an error which says "Invalid Authorization, please check if you copied it correctly" and then closes itself

**Comment by TheonlyIcebear** [comment]
Fixed

**Comment by b0ltcore** [comment]
Thanks, it opens but whenever it bets it crashes then gives me this error.

> ERROR:root:A error has occured at 17:25:08 05
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Bloxflip-Smart-Bet-main(2)\Bloxflip-Smart-Bet-main\Martingale.py", line 19, in __init__
    self.sendBets()
  File "C:\Users\admin\Desktop\Bloxflip-Smart-Bet-main(2)\Bloxflip-Smart-Bet-main\Martingale.py", line 378, in sendBets
    browser.find_element_by_css_selector(".MuiButtonBase-root.MuiButton-root.MuiButton-contained.jss142.MuiButton-containedPrimary").click()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 814, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1251, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".MuiButtonBase-root.MuiButton-root.MuiButton-contained.jss142.MuiButton-containedPrimary"}
  (Session info: chrome=102.0.5005.115)
Stacktrace:
Backtrace:
	Ordinal0 [0x00B2D953+2414931]
	Ordinal0 [0x00ABF5E1+1963489]
	Ordinal0 [0x009AC6B8+837304]
	Ordinal0 [0x009D9500+1021184]
	Ordinal0 [0x009D979B+1021851]
	Ordinal0 [0x00A06502+1205506]
	Ordinal0 [0x009F44E4+1131748]
	Ordinal0 [0x00A04812+1198098]
	Ordinal0 [0x009F42B6+1131190]
	Ordinal0 [0x009CE860+976992]
	Ordinal0 [0x009CF756+980822]
	GetHandleVerifier [0x00D9CC62+2510274]
	GetHandleVerifier [0x00D8F760+2455744]
	GetHandleVerifier [0x00BBEABA+551962]
	GetHandleVerifier [0x00BBD916+547446]
	Ordinal0 [0x00AC5F3B+1990459]
	Ordinal0 [0x00ACA898+2009240]
	Ordinal0 [0x00ACA985+2009477]
	Ordinal0 [0x00AD3AD1+2046673]
	BaseThreadInitThunk [0x760CFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77CC7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77CC7A4E+238]
