### ISSUE TITLE
Closes chrome after period of time

### ISSUE THREAD

**Issue by DesignedDeveloper** [TheonlyIcebear/Bloxflip-Smart-Bet#4]
Traceback (most recent call last):
  File "C:\\Bloxflip-Smart-Bet-main\main.py", line 239, in <module>
    main()
  File "C:\\Bloxflip-Smart-Bet-main\main.py", line 17, in __init__
    self.sendBets()
  File "C:\\Bloxflip-Smart-Bet-main\main.py", line 202, in sendBets
    for game in self.ChrashPoints():
  File "C:\Bloxflip-Smart-Bet-main\main.py", line 170, in ChrashPoints
    games = json.loads(data)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by max20211** [comment]
same

**Comment by TheonlyIcebear** [comment]
This is an issue with their cloudflare. If your using a vpn disconnect and next time it opens if there's a captcha try to solve it. I have also added some error handling to account for this as well.

**Comment by DesignedDeveloper** [comment]
don't use a vpn and no captcha

**Comment by TheonlyIcebear** [comment]
> don't use a vpn and no captcha

I have solved the problem by changing some problems on selenium
