### ISSUE TITLE
the problem

### ISSUE THREAD

**Issue by deezking** [TheonlyIcebear/Bloxflip-Smart-Bet#40]
ERROR:root:A error has occured at 23:25:13 11
Traceback (most recent call last):
  File "C:\Users\NB_NO\OneDrive\Desktop\New folder\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 19, in __init__
    self.getConfig()
  File "C:\Users\NB_NO\OneDrive\Desktop\New folder\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 277, in getConfig
    self.getBalance()
  File "C:\Users\NB_NO\OneDrive\Desktop\New folder\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 125, in getBalance
    balance = float(browser.find_element_by_css_selector(possibleclass).text.replace(',', ''))
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'

**Comment by wokedoss** [comment]
have you fixed it since not working for me too

**Comment by TheonlyIcebear** [comment]
Fixed
