### ISSUE TITLE
name 'cloudscraper' is not defined

### ISSUE THREAD

**Issue by Kherstine** [TheonlyIcebear/Bloxflip-Smart-Bet#62]
ERROR:root:A error has occured at 23:08:09 11
Traceback (most recent call last):
  File "Martingale.py", line 24, in __init__
  File "Martingale.py", line 392, in sendBets
  File "Martingale.py", line 122, in getBalance
NameError: name 'cloudscraper' is not defined

**Comment by Kherstine** [comment]
I already installed the requirements
