### ISSUE TITLE
issue with the uncompiled version

### ISSUE THREAD

**Issue by sedfsdfsdasdasdf** [TheonlyIcebear/Bloxflip-Smart-Bet#64]
ERROR:root:A error has occured at 00:53:35 12
Traceback (most recent call last):
  File "C:\Users\MYUSERPRIVATE\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\MYUSERPRIVATE\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\MYUSERPRIVATE\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\MYUSERPRIVATE\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\leaks\Bloxflip-Smart-Bet\Martingale.py", line 22, in __init__
    self.sendBets()
  File "D:\leaks\Bloxflip-Smart-Bet\Martingale.py", line 340, in sendBets
    for game in self.ChrashPoints():
  File "D:\leaks\Bloxflip-Smart-Bet\Martingale.py", line 303, in ChrashPoints
    games = scraper.get("https://rest-bf.blox.land/games/crash").json()
  File "C:\Users\MYUSERPRIVATE\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sedfsdfsdasdasdf** [comment]
reopened because keeps giving the error sometimes

**Comment by sedfsdfsdasdasdf** [comment]
![imagen](https://user-images.githubusercontent.com/73028283/185816285-45ecb302-f3e0-4154-8965-a2cacf2aa0f3.png)
also saying invalid auth

**Comment by TheonlyIcebear** [comment]
Fixed now
