### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by InsulatorGMan** [TheonlyIcebear/Bloxflip-Smart-Bet#67]
```
ERROR:root:A error has occured at 16:16:18 04
Traceback (most recent call last):
  File "C:\Users\hgco9\Music\Autofliip\Bloxflip-Smart-Bet-main\Martingale.py", line 24, in __init__
    self.getConfig()
  File "C:\Users\hgco9\Music\Autofliip\Bloxflip-Smart-Bet-main\Martingale.py", line 269, in getConfig
    self.hwid = current_machine_id = str(subprocess.check_output('wmic csproduct get uuid'), 'utf-8').split('\n')[1].strip()
  File "C:\Windows.old\Users\hgco9\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Windows.old\Users\hgco9\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Windows.old\Users\hgco9\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Windows.old\Users\hgco9\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by TheonlyIcebear** [comment]
Subprocess error
