### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by zohirben** [TheonlyIcebear/Bloxflip-Smart-Bet#68]
ERROR:root:A error has occured at 04:25:59 04
Traceback (most recent call last):
  File "Martingale.py", line 24, in __init__
  File "Martingale.py", line 392, in sendBets
  File "Martingale.py", line 122, in getBalance
NameError: name 'cloudscraper' is not defined

**Comment by AdamxzV3** [comment]
go into cmd and type this following command "pip install -r requirements.txt"

**Comment by TheonlyIcebear** [comment]
run installer.bat
