### ISSUE TITLE
Says config.json is missing but its not, I downloaded all files and edited the config.json but it still says its not there (but it is in my folder with all the other downloads)

### ISSUE THREAD

**Issue by ATTICUS34254567** [TheonlyIcebear/Bloxflip-Smart-Bet#70]
[ ERROR ] config.json file is missing. Make sure you downloaded all the files and they're all in the same folder
[ ERROR ] An error has occured check logs.txt for more info
Traceback (most recent call last):
  File "C:\Users\thoma\OneDrive\Documents\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 728, in <module>
    main()
  File "C:\Users\thoma\OneDrive\Documents\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 40, in __init__
    raise e
  File "C:\Users\thoma\OneDrive\Documents\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 28, in __init__
    self.getConfig()
  File "C:\Users\thoma\OneDrive\Documents\Bloxflip-Smart-Bet-main\Bloxflip-Smart-Bet-main\Martingale+Predictor (Paid).py", line 232, in getConfig
    with open("config.json", "r+") as data:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by TheonlyIcebear** [comment]
did you unzip the folder
